model_generated_outputs_path: "/data/btguan/pie/optm_generation/optm.jsonl"
reference_file_path: "/data/btguan/pie/optm_generation/test.jsonl" # The path to the reference file. This should be the reference .jsonl file containing the reference outputs in addition to all other metadata in the test set file.
output_dir: "./test_sep7_2"
is_prompt_based: False # should always be False
cpus_available: -1
model_generated_potentially_faster_code_col: "generated_answers" # column in the model-generated outputs that contains the generated code, it should be a list of strings
num_problems_to_evaluate: -1 # -1 means evaluate all problems
